name: PlatformIO CI

on:
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - '**/*.md'
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - '**/*.md'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: ~/.platformio/.cache
          key: ${{ runner.os }}-pio
          restore-keys: |
            ${{ runner.os }}-pio-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install PlatformIO
        run: |
          pip install --upgrade platformio

      - name: Build firmware
        run: |
          pio ci --project-conf=platformio.ini src

      - name: Instal wokwi CLI
        run: curl -L https://wokwi.com/ci/install.sh | sh

      - name: Test with Wokwi
        run: |
          pwd
          echo "${GITHUB_WORKSPACE}
          wokwi-cli --scenario=wokwi-scenario.yaml
        env:
          WOKWI_CLI_TOKEN: ${{ secrets.WOKWI_CLI_TOKEN }}
        shell: bash
        # uses: wokwi/wokwi-ci-action@v1
        # with:
        #   token: ${{ secrets.WOKWI_CLI_TOKEN }}
        #   path: / # directory with wokwi.toml, relative to repo's root
        #   timeout: 10000
        #   scenario: 'wokwi-scenario.yaml'
        #   serial_log_file: 'serial.log'
        #   elf: .pio/build/nano/firmware.elf






