name: PlatformIO CI

on:
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - '**/*.md'
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - '**/*.md'
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: ~/.platformio/.cache
          key: ${{ runner.os }}-pio
          restore-keys: |
            ${{ runner.os }}-pio-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install PlatformIO
        run: |
          curl https://raw.githubusercontent.com/platformio/platformio-core-installer/master/get-platformio.py | python3

     - name: Build firmware
       run: |
         pio ci --project-conf=platformio.ini src

      - name: Test with Wokwi
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          path: / # directory with wokwi.toml, relative to repo's root
          timeout: 10000
          scenario: 'wokwi-scenario.yaml'
          serial_log_file: 'serial.log'






