name: PlatformIO

on: pull_request

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.2'
          cache: 'pip' # caching pip dependencies
        env:
          AGENT_TOOLSDIRECTORY: /home/debian/hostedtoolcache
      - run: python3 -m pip install platformio
        env:
          AGENT_TOOLSDIRECTORY: /home/debian/hostedtoolcache       
      - name: PlatformIO Run
        uses: karniv00l/platformio-run-action@v1
        with:
          environments: "nanoatmega328,uno"
          targets: "nanoatmega328"
          project-dir: "."
          project-conf: "./platformio.ini"
          jobs: 1
          silent: false
          verbose: true
          disable-auto-clean: false
