name: PlatformIO

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: pio run
        env:
          PATH: "/home/debian/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
          AGENT_TOOLSDIRECTORY: /home/debian/hostedtoolcache       
