name: PlatformIO Flow

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: adafruit/ci-arduino
          path: ci
      # - name: pre-install
      #   run: python3 -m venv .venv && source .venv/bin/activate && bash ci/actions_install.sh
      # - name: test platforms
      #   run: .venv/bin/python3 ci/build_platform.py main_platforms
      - name: clang
        run: python3 ci/run-clang-format.py -e "ci/*" -e "bin/*" -r .       
      - uses: actions/checkout@v4
      - run: pio run
        env:
          PATH: "/home/debian/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
          AGENT_TOOLSDIRECTORY: /home/debian/hostedtoolcache       
