name: PlatformIO

on: pull_request

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: PlatformIO Run
        uses: karniv00l/platformio-run-action@v1
        with:
          environments: "nanoatmega328,uno"
          targets: "nanoatmega328"
          project-dir: "."
          project-conf: "./platformio.ini"
          jobs: 1
          silent: false
          verbose: true
          disable-auto-clean: false
